export const ROLES = {
  ADMIN: "Admin",
  GENERAL: "General",
  ANAGESSA: "ANAGESSA",
  RESPONSABLE: "mais_Responsable",
  SOCIETE: "Anagessa_Chef_societe",
  SUPERVISEUR_REGIONAL: "Superviseur_Regional",
  SUPERVISEUR: "Superviseur",
  LABORATOIRE: "Respo_labo",
  UDP: "Respo_usine_deparchage",
};

export const ROUTE_PERMISSIONS = {
  "/anagessa-dashboard/collectors": [ROLES.ADMIN],
  "/anagessa-dashboard/societies": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SUPERVISEUR,
  ],
  "/anagessa-dashboard/payments": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/anagessa-dashboard/home": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],

  "/anagessa-dashboard/cultivators": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/anagessa-dashboard/hangarss": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/anagessa-dashboard/usine": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SUPERVISEUR,
  ],
  "/anagessa-dashboard/stocks": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/anagessa-dashboard/stocks/achats": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],

  "/anagessa-dashboard/stocks/transfers": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/anagessa-dashboard/maps": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/anagessa-dashboard/maps": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ANAGESSA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/anagessa-production/usine/reception": [ROLES.ADMIN, ROLES.UDP],
  "/anagessa-production/usine/stockage": [ROLES.ADMIN, ROLES.UDP],
  "/anagessa-production/usine/triage": [ROLES.ADMIN, ROLES.UDP],
  "/anagessa-production/usine/usinage": [ROLES.ADMIN, ROLES.UDP],
  "/anagessa-production/laboratoire/reception": [ROLES.ADMIN, ROLES.LABORATOIRE],
  "/anagessa-production/laboratoire/granulometrie": [
    ROLES.ADMIN,
    ROLES.LABORATOIRE,
  ],
  "/anagessa-production/laboratoire/triage": [ROLES.ADMIN, ROLES.LABORATOIRE],
  "/anagessa-production/laboratoire/cupping": [ROLES.ADMIN, ROLES.LABORATOIRE],
  "/anagessa-production/laboratoire/rapports": [ROLES.ADMIN, ROLES.LABORATOIRE],
};
